### ISSUE TITLE
Notifications show in recording

### ISSUE THREAD

**Issue by dsandstrom** [lexcast/screen-recorder#4]
If my window is small and I'm recording a selected area, the start notification shows in my recording.  I'm not sure a good way to prevent this, other than make my window wider and make sure I don't select where the notification will show.

**Comment by lexcast** [comment]
Yes, maybe I should remove those notifications.

**Comment by dsandstrom** [comment]
Maybe.  However, it is useful to have have visual feedback.  I guess you could make it an option.

**Comment by lexcast** [comment]
Maybe an option, but there is already another visual indicator on the status bar. We could keep only the cancel and saved notifications.

**Comment by dsandstrom** [comment]
Sounds good to me.

**Comment by lexcast** [comment]
fixed now
