### ISSUE TITLE
Select Area doesn't seem to work on Ubuntu 14.04

### ISSUE THREAD

**Issue by FHeilmann** [lexcast/screen-recorder#7]
Hi, Just discovered this plugin and love it. However I have an issue:

The select area function doesn't work for me. Whenever I execute the command, a black bar shows up in the middle of my buffer window and I cannot resize/click/do anything until I restart atom.

Using latest screen-recorder version and atom 1.13.0 on ubuntu 14.04 with imagemagick from apt and a static ffmpeg build

edit: Everything else works as expected.

**Comment by lexcast** [comment]
@FHeilmann sorry for the delay, can you provide a screenshot?

**Comment by FHeilmann** [comment]
![rec](https://cloud.githubusercontent.com/assets/4352664/23695088/da77382e-03dd-11e7-8eae-e4483229f9e4.gif)

I (in the meantime) updated to Ubuntu 16.04.02 and atom 1.14.4 where the issue is still there.

**Comment by lexcast** [comment]
Probably some styles are affecting that panel, inspect the panel with the dev tools, open it with the command: `Window: Toggle Dev Tools`. 
Which theme is?

**Comment by FHeilmann** [comment]
It's the One Dark theme that ships with Atom.
Log output doesn't show anything interesting, and I cannot inspect the element using the "Elements" Tab.

**Comment by lexcast** [comment]
now I see it, I confirmed the bug

Thank you, I'll try to fix it
